scene: dog
source_path: data_hdr/synthetic/dog
method: mlp

# llff parameters
dataset_type: syn_llff
factor: 4
llffhold: 0
max_exp: 0.166667
min_exp: 0.166667
fixed_value: 0.73
use_viewdirs: True
recenter: True
bd_factor: 0.75
images: images
render_video: True
video_render_exps: [0.05, 10.0]


# Gaussian Parameters
convert_SHs_python: True
iterations: 30_000
position_lr_init: 0.00016
position_lr_final: 0.0000016
position_lr_delay_mult: 0.01
position_lr_max_steps: 30_000
feature_lr: 0.0028
opacity_lr: 0.05
scaling_lr: 0.005
rotation_lr: 0.001
percent_dense: 0.01
lambda_dssim: 0.4
densification_interval: 80
opacity_reset_interval: 3000
densify_from_iter: 500
densify_until_iter: 15_000
densify_grad_threshold: 0.00017
random_background: False
exps_loss_weight: 0.5

# tone mapper parameters
tone_mapper_r_lr_init: 0.0005
tone_mapper_r_lr_final: 0.00005
tone_mapper_r_lr_delay_mult: 0.01
tone_mapper_r_lr_max_steps: 30_000
tone_mapper_g_lr_init: 0.0005
tone_mapper_g_lr_final: 0.00005
tone_mapper_g_lr_delay_mult: 0.01
tone_mapper_g_lr_max_steps: 30_000
tone_mapper_b_lr_init: 0.0005
tone_mapper_b_lr_final: 0.00005
tone_mapper_b_lr_delay_mult: 0.01
tone_mapper_b_lr_max_steps: 30_000